<div data-dojo-type="dijit/TitlePane" data-dojo-props="title: 'Slide # <?php echo $this->model->slideId;?> Current Order: <?php echo $this->model->order; ?>', open: false">
    <div class="slideDetails">
        <div class="slideImage">
            <img class="pane" src="modules/slider/_thumbs/<?php echo  'resized_'.$this->model->image;?>" width="200" height="121" style="display:block; overflow:hidden;" />
        </div>
        <div class="slideContent">
            <?php 
            if(isset($this->model->content)) {
            ?>
                <p><?php echo $this->model->content; ?></p>
            <?php 
            }
            ?>
            
        </div>
        <div class="slideActions">
            <?php 
//             if ($acl->isAllowed($role, 'admin:area', 'admin:edit'))
//             {
            ?>
                <ul style="list-style: none;">
                    <li><?php echo $this->button(null, '/admin/slider/delete/' . $this->model->slideId, array('label' => 'Delete'), array('class' => 'adminUiButton')); ?></li>
                    <li><?php echo $this->button(null, '/admin/slider/edit/' . $this->model->slideId, array('label' => 'Edit'), array('class' => 'adminUiButton')); ?></li>
                </ul>
            <?php 
            //}
            ?>
        </div>
    </div>
</div>