<?php if ($this->pageCount > 1): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>

<?php echo '<a href="/search/results?page='.$this->previous.'&amp;term='.$this->term.'">&lt; Previous</a>'?> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
  
  <?php echo '<a href="/search/results?page='.$page.'&amp;term='.$this->term.'">'.$page.'</a>'?>
   |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>

 <?php echo '<a href="/search/results?page='.$this->next.'&amp;term='.$this->term.'">Next &gt</a>'?>

<?php else: ?>
  <span class="disabled">Next &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>