<div class="ui-products">

<?php
	if(isset($this->paginator) && ($this->paginator instanceof Zend_Paginator)) {
		$this->partialLoop()->setObjectKey('model');
		echo $this->partialLoop('/partials/ui-admin-products.phtml', $this->paginator);

		if($this->paginator->count() > 1) {
			echo $this->paginationControl($this->paginator, 'Sliding', 'partials/ui-pagination-control.phtml');
		}
	}
	if( $this->acl->isAllowed($this->user->role, $this->module,  'resource.products.manage') ) {
?>
		<a class="button" href="/admin/products/create">Add New Product</a>
<?php
	}
?>

</div>

