<div data-role="page" data-control-title="AdminIndex" id="admin-index">
    <div data-theme="b" data-role="header" data-add-back-btn="true">
        <h3>
            Site Administration
        </h3>
        <!-- This must remain this way so as to provide a href to link back to the home page -->
        <a data-role="button" href="/" data-icon="arrow-l" data-iconpos="left" class="ui-btn-left">Back</a>
    </div>
    <div data-role="content">
        <ul data-role="listview" data-divider-theme="b" data-inset="true">
            <li data-role="list-divider" role="heading">
            </li>
            <li data-theme="c">
                <a href="/admin/page/manager" data-transition="slide">
                    Content
                </a>
            </li>
            <li data-theme="c">
                <a href="/admin/contact" data-transition="slide">
                    Contact
                </a>
            </li>
            <li data-theme="c">
                <a href="/admin/settings" data-transition="slide">
                    Settings
                </a>
            </li>
        </ul>
    </div>
</div>

