<div id="page-content" class="prefix_4 grid_8">
		<div class="ui-login ui-corner-all">
		<div class="ui-widget-header ui-corner-top">
			<div class="ui-pages-heading">
				<h2>Login</h2>
			</div>
		</div>
			<div class="ui-helper-clearifx ui-widget-content ui-corner-bottom ui-helper-clearfix">
				<ul class="navigation">
					<li><a href="/user/admin/edit/<?php echo $userInfo->userId; ?>">Edit Personal Info</a></li>
				</ul>
			</div>
		</div>
</div>