<?php
echo $this->doctype();
?>
<html>
<head>

<base href="<?php echo $this->serverUrl($this->baseUrl('/')); ?>" />

<?php
echo $this->headMeta();
echo $this->headTitle();

$this->headLink()
    ->prependStylesheet('/lib/dijit/themes/claro/claro.css', 'screen')
    ->headLink()
    ->appendStylesheet('/skins/default/admin/style.css', 'screen');

echo $this->headLink(); // will push style sheets onto stack as needed, do not remove
    
$this->headScript()->offsetSetScript(0, 
'dojoConfig = {
	async: true,
	parseOnLoad: true,
	dojoBlankHtmlUrl: "/lib/dojo/resources/blank.html",
	ioPublish: true,
	packages: [
	     {
	    	 name: "aurora",
	         location: "/lib/aurora"
	     }
	]
};');

// call the local dojo build file and set its index count to 1 as it should be the first to load in the stack
$this->headScript()->offsetSetFile(1, '/lib/dojo/dojo.js');
//push our app setup script
$this->headScript()->offsetSetScript(2, 'require([
"dojo/dom",
"aurora/admin/app"
],
   function(dom, app){
   app.init();	
});');
?>
<?php 
// finally print this as everything else will be pushed onto the stack within a view file
echo $this->headScript();
?>
<body class="claro">
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'headline', gutters: 'true' "style="z-index: 0; width: 100%; height: 100%;">
		<div data-dojo-id="headerPane" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: 'true'">
		
		<?php 
		echo $this->navigation()->menu()->renderPartial(Zend_Registry::get('Admin_Navigation'), '/admin/partials/main-menubar.phtml');
		?>
		
		</div>
		<div id="wSO" data-dojo-id="wSO" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', splitter: 'false', parseOnLoad: 'true'">
		  <?php 
            echo $this->layout()->content;
          ?>
		</div>
		<div data-dojo-id="footerPane" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'bottom', splitter: 'true'">
		System Status
		</div>
	</div>
    </body>
</html>