<?php
	echo $this->doctype();
?>
<html>
<head>

<base href="<?php echo $this->serverUrl($this->baseUrl('/')); ?>" />

<?php
	echo $this->headMeta();
    echo $this->headTitle();
	echo $this->headLink()
                ->prependStylesheet('/lib/dijit/themes/claro/claro.css', 'screen')
                ->headLink()
                ->appendStylesheet('/skins/' . Zend_Registry::get('skinName') . '/style.css', 'screen');
?>

<script>
dojoConfig = {
	async: true,
	parseOnLoad: true,
	dojoBlankHtmlUrl: "/lib/dojo/resources/blank.html",
	ioPublish: true,
	has: {
       "dojo-firebug": true,
       "dojo-debug-messages": true
	},
	packages: [
	     {
	    	 name: "aurora",
	         location: "/lib/aurora"
	     }
	],
	app: {

	},
	// Get "fresh" resources
	cacheBust: true
};
</script>
<script src="//ajax.googleapis.com/ajax/libs/dojo/1.9.1/dojo/dojo.js"></script>
<script type="text/javascript">
require([
	"aurora/app",
]);
</script>
</head>
<body class="claro">
	<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design: 'headline', gutters: 'true'" style="z-index: 0; width: 100%; height: 100%;">
		<div data-dojo-id="header" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: 'true'">
		<?php 
		try {
			echo $this->navigation()->menu();
		} catch (Zend_Exception $e) {
            //echo $e->getMessage();
		}
			
		?>
		</div>
 		<div data-dojo-id="bodyContentPanel" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', spliter: 'true'"> 
		<?php 
            echo $this->layout()->content;
        ?>
		</div> 
		<div data-dojo-id="footer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'bottom', splitter: 'true'">
		<?php 
			echo $this->copyright();
		?>
		</div>
	</div>
</body>
</html>