<?php
if ($this->pageCount > 1):
?>
<div class="paginationControl buttonset">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>

<a id="previous" class="ajax-control" href="<?php echo $this->url(array(
																'parentCat' => $this->parentCat,
																'childCat'  => $this->childCat,
																'page' => $this->previous

															)); ?>">&laquo; Previous</a>
<?php else : ?>
<a class="disabled"><span>&laquo; Previous</span></a>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
  <a id="page" class="ajax-control" href="<?php echo $this->url(array(
	  														'parentCat' => $this->parentCat,
	  														'childCat'  => $this->childCat,
  															'page' => $page
  															)); ?>"><?php echo $page; ?></a>
  <?php else: ?>
  <a id="current" class="ajax-control" href="<?php echo $this->url(array(
    																'parentCat' => $this->parentCat,
    																'childCat'  => $this->childCat,
    																'page' => $this->current
    																)); ?>"><?php echo $this->current; ?></a>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a id="next" class="ajax-control" href="<?php echo $this->url(array(
  																'parentCat' => $this->parentCat,
  																'childCat'  => $this->childCat,
  																'page' => $this->next
  																)); ?>">Next &raquo;</a>
<?php else : ?>
<a class="disabled">Next &raquo;</a>
<?php endif; ?>
</div>
<?php endif; ?>

