; set a plugin path to use the resource class
; see: http://framework.zend.com/manual/en/zend.application.available-resources.html

resources.router.routes.admin-user-index.route = /admin/user/:page/:sort
resources.router.routes.admin-user-index.defaults.module = user
resources.router.routes.admin-user-index.defaults.controller = admin
resources.router.routes.admin-user-index.defaults.action = index
resources.router.routes.admin-user-index.defaults.page = 1
resources.router.routes.admin-user-index.defaults.sort = "byId"
;resources.router.routes.admin-user-index.defaults.format = "html"

resources.router.routes.admin-user-create.route = /admin/user/create
resources.router.routes.admin-user-create.defaults.module = user
resources.router.routes.admin-user-create.defaults.controller = admin
resources.router.routes.admin-user-create.defaults.action = create
;resources.router.routes.admin-user-create.defaults.format = "html"

resources.router.routes.admin-user-edit.route = /admin/user/edit/:id/:page
resources.router.routes.admin-user-edit.defaults.module = user
resources.router.routes.admin-user-edit.defaults.controller = admin
resources.router.routes.admin-user-edit.defaults.action = edit
resources.router.routes.admin-user-edit.defaults.page = 1
;resources.router.routes.admin-user-edit.defaults.format = "html"

resources.router.routes.admin-user-delete.route = /admin/user/delete/:id/:page
resources.router.routes.admin-user-delete.defaults.module = user
resources.router.routes.admin-user-delete.defaults.controller = admin
resources.router.routes.admin-user-delete.defaults.action = delete
resources.router.routes.admin-user-delete.defaults.page = 1


resources.router.routes.admin-user-list.route = /admin/user/list/:page/:format
resources.router.routes.admin-user-list.defaults.module = user
resources.router.routes.admin-user-list.defaults.controller = admin
resources.router.routes.admin-user-list.defaults.action = list
resources.router.routes.admin-user-list.defaults.page = 1
resources.router.routes.admin-user-list.defaults.format = "html"

resources.router.routes.user-login-index.route = /user/login
resources.router.routes.user-login-index.defaults.module = user
resources.router.routes.user-login-index.defaults.controller = user.login
resources.router.routes.user-login-index.defaults.action = index

resources.router.routes.user-login-devlogin.route = /user/login/dev
resources.router.routes.user-login-devlogin.defaults.module = user
resources.router.routes.user-login-devlogin.defaults.controller = user.login
resources.router.routes.user-login-devlogin.defaults.action = devlogin

resources.router.routes.user-login-success.route = /user/login/success
resources.router.routes.user-login-success.defaults.module = user
resources.router.routes.user-login-success.defaults.controller = user.login
resources.router.routes.user-login-success.defaults.action = success

resources.router.routes.user-login-logout.route = /user/login/logout
resources.router.routes.user-login-logout.defaults.module = user
resources.router.routes.user-login-logout.defaults.controller = user.login
resources.router.routes.user-login-logout.defaults.action = logout

resources.router.routes.user-register-index.route = /user/register
resources.router.routes.user-register-index.defaults.module = user
resources.router.routes.user-register-index.defaults.controller = user.register
resources.router.routes.user-register-index.defaults.action = index

resources.router.routes.user-register-verify.route = /user/register/verify/:uid/:hash
resources.router.routes.user-register-verify.defaults.module = user
resources.router.routes.user-register-verify.defaults.controller = user.register
resources.router.routes.user-register-verify.defaults.action = verify

resources.router.routes.user-register-success.route = /user/register/success
resources.router.routes.user-register-success.defaults.module = user
resources.router.routes.user-register-success.defaults.controller = user.register
resources.router.routes.user-register-success.defaults.action = success

resources.router.routes.user-account-summary.route = /user/account/summary
resources.router.routes.user-account-summary.defaults.module = user
resources.router.routes.user-account-summary.defaults.controller = user.account
resources.router.routes.user-account-summary.defaults.action = summary

resources.router.routes.user-account-details.route = /user/account/details/:userId
resources.router.routes.user-account-details.defaults.module = user
resources.router.routes.user-account-details.defaults.controller = user.account
resources.router.routes.user-account-details.defaults.action = details


; User_UserController routes - is working
resources.router.routes.user-user-index.route = /user/index
resources.router.routes.user-user-index.defaults.module = user
resources.router.routes.user-user-index.defaults.controller = user
resources.router.routes.user-user-index.defaults.action = index

resources.router.routes.user-products-display.route = /user/products/display/:prod_id
resources.router.routes.user-products-display.defaults.module = user
resources.router.routes.user-products-display.defaults.controller = user.products
resources.router.routes.user-products-display.defaults.action = display

resources.router.routes.user-products-products.route = /user/products/page/:page
resources.router.routes.user-products-products.defaults.module = user
resources.router.routes.user-products-products.defaults.controller = user.products
resources.router.routes.user-products-products.defaults.action = products
resources.router.routes.user-products-products.defaults.page = 1

