<?php 
echo $this->button(null, '/admin/slider/create', array('label' => 'New Slide'), array('class' => 'adminUiButton')); 
if ($this->paginator instanceof Zend_Paginator) {
    $this->paginator->setItemCountPerPage(5);
		$this->partialLoop()->setObjectKey('model');
		
		if($this->paginator->count() > 1) {
		    echo $this->paginationControl($this->paginator,'Sliding','dojo-dropdown-pagination-control.phtml', array('page' => $this->page));
		}
		
		echo $this->partialLoop('slider/manager-item.phtml', $this->paginator);
}
?>
