<div id="pageManagerCmdMenu" data-dojo-type="dijit/MenuBar">
    <!-- start drop down tab -->
    <div data-dojo-type="dijit/PopupMenuBarItem">
        <span>Collections</span>
        <div data-dojo-type="dijit/DropDownMenu">
            <div data-dojo-type="dijit/MenuItem" cmd="/admin/page/create/collection">
            New Collection
            </div>
            <div data-dojo-type="dijit/MenuItem" cmd="/admin/page/manage/collection">
            Manage Existing
            </div>
        </div>
    </div>
    <!-- end drop down tab -->
    <!-- start main tab -->
    <div data-dojo-type="dijit/MenuBarItem" cmd="/some/location">Main Label</div>
    <!-- end main tab -->
</div>
