<?php 
if ($this->pageCount) { 
?>
<div data-dojo-type="dijit/DropDownMenu" id="dojoPaginationControl">
    <div data-dojo-type="dijit/PopupMenuItem">
        <span>Jump to Page: </span>
        <div data-dojo-type="dijit/DropDownMenu" id="dojoPaginationPageList">
            <?php 
            foreach ($this->pagesInRange as $page) {
            ?>
                <div data-dojo-type="dijit/MenuItem" cmd="<?php echo $this->url(array('page' => $page));?>"><?php echo $page; ?></div>
            <?php 
            }
            ?>
        </div>
    </div>
</div>
<?php 
}
?>

