<div data-role="page" data-control-title="settings" id="page2">
    <div data-theme="b" data-role="header" data-add-back-btn="true">
        <span class="ui-title">
        </span>
    </div>
    <div data-role="content">
        <ul data-role="listview" data-divider-theme="b" data-inset="true">
            <li data-role="list-divider" role="heading">
            </li>
            <li data-theme="c">
                <a href="/admin/contact/settings" data-transition="slide">
                    Contact Settings
                </a>
            </li>
            <li data-theme="c">
                <a href="/admin/user/settings" data-transition="slide">
                    User Settings
                </a>
            </li>
            <li data-theme="c">
                <a href="/admin/page/settings" data-transition="slide">
                    Page Settings
                </a>
            </li>
        </ul>
    </div>
</div>
