<?php
if ($this->paginator instanceof Zend_Paginator) {
    $this->paginator->setItemCountPerPage(2);
		$this->partialLoop()->setObjectKey('model');
		
		if($this->paginator->count() > 1) {
		    echo $this->paginationControl($this->paginator,'Sliding','dojo-dropdown-pagination-control.phtml', array('page' => $this->page));
		}
		
		echo $this->partialLoop('user/admin-userlist-ui-widget.phtml', $this->paginator);
}
?>

