<?php if ($this->pageCount): ?>
    <div class="pagination">
     <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
     <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
     &laquo;&nbsp;Previous
      </a> <span class="bar"> | </span>
      <?php else: ?>
      <span class="disabled">&laquo;&nbsp;Previous</span><span class="bar"> | </span>
<?php endif; ?>
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> <span class="bar"> | </span>
  <?php else: ?>
    <?php echo $page; ?> <span class="bar"> | </span>
  <?php endif; ?>
<?php endforeach; ?>
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next&nbsp;&raquo;
  </a>
<?php else: ?>
  <span class="disabled">Next&nbsp;&raquo; </span>
<?php endif; ?>
</div>
<?php endif; ?>