<?php
	echo $this->doctype();
?>
<html>
<head>

<base href="<?php echo $this->serverUrl($this->baseUrl('/')); ?>" />

<?php
	echo $this->headMeta();
    echo $this->headTitle();
	echo $this->headLink()
                ->prependStylesheet('/lib/dijit/themes/claro/claro.css', 'screen')
                ->headLink()
                ->appendStylesheet('/skins/' . Zend_Registry::get('skinName') . '/style.css', 'screen');
?>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300italic,400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Merriweather:400,700,700italic,400italic' rel='stylesheet' type='text/css'>
<script>
dojoConfig = {
	async: true,
	parseOnLoad: true,
	dojoBlankHtmlUrl: "/lib/dojo/resources/blank.html",
	ioPublish: true,
	has: {
       "dojo-firebug": true,
       "dojo-debug-messages": true
	},
	packages: [
	     {
	    	 name: "aurora",
	         location: "/lib/aurora"
	     }
	],
	app: {

	},
	// Get "fresh" resources
	cacheBust: false
};
</script>
<script src="//ajax.googleapis.com/ajax/libs/dojo/1.9.1/dojo/dojo.js"></script>
<script type="text/javascript">
require([
	"aurora/app",
]);
</script>
</head>
<body class="claro">
	<div data-dojo-type="dijit/layout/LayoutContainer" data-dojo-props="design: 'headline', gutters: 'false'" style="z-index: 0; width: 100%; height: 100%;">
	<div data-dojo-id="bodyContentPanel" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'center', spliter: 'false'" style="padding: 0; margin: 0;"> 
		<div id="header" data-dojo-id="header" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'top', splitter: 'false'">
		  <div id="header-content">
		      <h1><?php echo '<a href="/" title="' . $this->appSettings->siteName . '"><img src="skins/' . Zend_Registry::get('skinName') . '/images/tqi_logo.png" width="168" height="153" /></a>'; ?></h1>
		      <?php 
			     echo $this->navigation()->menu();
		      ?>
		  </div>
		</div>
 		
		<?php 
            echo $this->layout()->content;
        ?>
		</div> 
		<div id="footer" data-dojo-id="footer" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region: 'bottom', splitter: 'false'">
		  <div class="left">
		      <span>
		          <?php 
		              echo $this->appSettings->siteName;
		          ?>
		      </span>
		      <span>
		          <?php 
		              echo $this->appSettings->addressLine1 . ' | ' . $this->appSettings->addressLine2 . ' Fax: ' . $this->appSettings->contactFaxNumber;
		          ?>
		      </span>
		      <span>
		          <?php 
		              echo 'Phone: ' . $this->appSettings->contactPhoneNumber . ' Email: ' . $this->appSettings->emailAddress;
		          ?>
		      </span>
		      <?php 
		          echo $this->socialMedia(); 
		      ?>
		  </div>
		  <?php 
			 echo $this->copyright();
		  ?>
		</div>
    </div>
</body>
</html>