<?php
//$this->jQuery()->addStylesheet('/js-src/jquery-core/plugins/slider/css/anythingslider.css');
$this->headLink()->appendStylesheet('/js-src/jquery-core/plugins/slider/css/anythingslider.css', 'screen');
//$this->jQuery()->addJavascriptFile('/js-src/jquery-core/plugins/slider/jquery.easing.1.2.js');
$this->jQuery()->addJavascriptFile('/js-src/jquery-core/plugins/slider/jquery.anythingslider.'.APPLICATION_ENV.'.js');
$this->jQuery()->addJavascriptFile('/js-src/jquery-core/plugins/slider/jquery.anythingslider.fx.'.APPLICATION_ENV.'.js');

/*
 * 											        effect: "'.$this->sliderSettings->effect.'",
											        slices: '.$this->sliderSettings->slices.',
											        boxCols: '.$this->sliderSettings->boxCols.',
											        boxRows: '.$this->sliderSettings->boxRows.',
											        animSpeed: '.$this->sliderSettings->animSpeed.',
											        pauseTime: '.$this->sliderSettings->pauseTime.',
											        startSlide: '.$this->sliderSettings->startSlide.',
											        directionNav: '.$this->sliderSettings->directionNav.',
											        controlNav: '.$this->sliderSettings->controlNav.',
											        controlNavThumbs: '.$this->sliderSettings->controlNavThumbs.',
											        pauseOnHover: '.$this->sliderSettings->pauseOnHover.',
											        manualAdvance: '.$this->sliderSettings->manualAdvance.',
											        prevText: "'.$this->sliderSettings->prevText.'",
											        nextText: "'.$this->sliderSettings->nextText.'",
											        randomStart: '.$this->sliderSettings->randomStart.',
 */

?>


		<div class="grid_4">
			<div class="ui-widget-content">
				<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
				Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
				It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
				It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
			</div>
		</div>

	<div class="grid_12">
		<ul id="slider">
			<?php
			$this->partialLoop()->setObjectKey('model');
			echo $this->partialLoop('/partials/ui-slider.phtml', null, $this->images);
			?>
		</ul>
	</div>

<?php
$this->headStyle()->captureStart();
?>
.anythingSlider-default {
    margin: 0;
    padding: 0;
}

#slider {
  width:100%;
  list-style: none;
  box-shadow: 5px #555;
 }
 /* images with caption */
 #slider img {
  width: 100%;
  height: 100%;
 }
 /* override the default themes colors for this site */
 .anythingSlider-default.activeSlider .anythingControls a.start-stop.playing {
  background-color: #437F1E;
  color: #FFFFFF;
}
 /* position the panels so the captions appear correctly */
 #slider .panel { position: relative; }
 /* captions */
 #slider .caption-top, #slider .caption-right,
 #slider .caption-bottom, #slider .caption-left {
  background: #fff;
  color: #437F1E;
  padding: 10px;
  margin: 0;
  position: relative;
  z-index: 10;
  /*opacity: 100;
  filter: alpha(opacity=100);*/
 }
 /* Top caption - padding is included in the width (480px here, 500px in the script), same for height */
 #slider .caption-top {
  left: 0;
  top: 0;
  width: 480px;
  height: 30px;
 }
 /* Right caption - padding is included in the width (130px here, 150px in the script), same for height */
 #slider .caption-right {
  right: 0;
  bottom: 0;
  width: 130px;
  height: 180px;
 }
 /* Bottom caption - padding is included in the width (480px here, 500px in the script), same for height */
 #slider .caption-bottom {
  left: 0;
  bottom: 0;
  width: 100%;
  height: 30px;
 }
 /* Left caption - padding is included in the width (130px here, 150px in the script), same for height */
 #slider .caption-left {
  left: 0;
  bottom: 0;
  width: 130px;
  height: 180px;
 }
 /* Caption close button */
 .caption-top .close, .caption-right .close,
 .caption-bottom .close, .caption-left .close {
  font-size: 80%;
  cursor: pointer;
  float: right;
  display: inline-block;
 }
/* .caption-bottom span.slider-title {
  font-size: 1.5em;
 }
 .caption-bottom p.slider-description {
 font-size: 1.25em;
 margin-right: 1em;
 float:right;
 }*/
 <?php
 $this->headStyle()->captureEnd();
 ?>